/*
---
template_id: L1/components/collapsible
layer: L1
provenance_class: external_canonical
evidence:
  - source_type: upstream_id
    upstream_id: shadcn-ui-2026-05
    section: collapsible
    quote: "An interactive component which expands/collapses a panel."
  - source_type: external
    citation: "WCAG 2.2 SC 4.1.2 Name, Role, Value (Level A) — full normative text, W3C Recommendation 2023-10-05"
    url: "https://www.w3.org/TR/WCAG22/#name-role-value"
    quote: "For all user interface components (including but not limited to: form elements, links and components generated by scripts), the name and role can be programmatically determined; states, properties, and values that can be set by the user can be programmatically set; and notification of changes to these items is available to user agents, including assistive technologies."
    quoted_at: "2026-07-29"
a11y_criteria:
  - "WCAG 2.2 SC 4.1.2 — aria-expanded managed by Radix"
  - "WCAG 2.2 SC 2.4.11 Focus Appearance"
  - "Trigger must be a <button> not a styled <div>"
dependencies: ["@radix-ui/react-collapsible"]
drift_snapshot_ref: "practices-react/upstream/shadcn-registry-2026-05.snapshot.md#collapsible"
---
*/
import * as CollapsiblePrimitive from '@radix-ui/react-collapsible'

const Collapsible = CollapsiblePrimitive.Root
const CollapsibleTrigger = CollapsiblePrimitive.CollapsibleTrigger
const CollapsibleContent = CollapsiblePrimitive.CollapsibleContent

export { Collapsible, CollapsibleTrigger, CollapsibleContent }
