-- V029__create_consent_records.sql
-- Consent ledger schema (IMW5). Reference migration for production Postgres deployments.
--
-- NOTE: Flyway is not on the runtime classpath in this template — Hibernate
-- ddl-auto=create-drop manages the H2 reference workload. This file documents
-- the migration that a Flyway-enabled production deployment would execute.
-- The DDL is intentionally identical to what JPA derives from
-- com.ax.template.authblueprint.common.ConsentRecord so future Flyway adoption
-- is a drop-in.
--
-- specs/consent-management-l0.yaml#CONSENT-RECORD-001 (GDPR Art 7(1) demonstrate
-- consent): consent_records is an APPEND-ONLY ledger. Every consent state change
-- appends one row (action GRANT|WITHDRAW); a withdrawal NEVER updates or deletes
-- the prior GRANT row. "Current consent" is the latest action per
-- (subject_id, purpose) — a derived query (common/ConsentGate.activeConsent), not
-- a mutable column. @Column(updatable=false) on every entity field enforces
-- immutability at the application layer. Production Postgres should additionally
-- install a row-level trigger that raises on UPDATE/DELETE and revoke
-- UPDATE/DELETE privileges from the application role.

CREATE TABLE IF NOT EXISTS consent_records (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    subject_id   VARCHAR(255) NOT NULL,
    purpose      VARCHAR(128) NOT NULL,
    action       VARCHAR(16)  NOT NULL,
    recorded_at  TIMESTAMP    NOT NULL
);

-- Current-state derivation scans the ledger by (subject, purpose) and takes the
-- latest recorded_at — index that access path.
CREATE INDEX IF NOT EXISTS ix_consent_records_subject_purpose
    ON consent_records(subject_id, purpose, recorded_at);
