#!/usr/bin/env bash
# skills/ax-scaffold/scripts/new-domain.sh — Tier-1 domain scaffolder.
#
# Generates the Spec Trio skeleton for a new domain per METHODOLOGY.md Appendix C.
# Accepts a required <domain> argument and an optional --dry-run flag.
#
# Exit 0 = files written (or plan printed in dry-run mode)
# Exit 1 = validation error (DOMAIN_EXISTS, INVALID_NAME, MISSING_METHODOLOGY)
#
# Usage:
#   bash skills/ax-scaffold/scripts/new-domain.sh <domain-name> [--dry-run]
set -uo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/../../.." && pwd)"

# ── Parse args ────────────────────────────────────────────────────────────────
DOMAIN=""
DRY_RUN=0

for arg in "$@"; do
    case "$arg" in
        --dry-run) DRY_RUN=1 ;;
        -*) echo "new-domain: ERROR — unknown flag: $arg" >&2; exit 1 ;;
        *)
            if [ -n "$DOMAIN" ]; then
                echo "new-domain: ERROR — multiple domain names provided: '$DOMAIN' and '$arg'" >&2
                exit 1
            fi
            DOMAIN="$arg"
            ;;
    esac
done

# ── Validate domain name ──────────────────────────────────────────────────────
if [ -z "$DOMAIN" ]; then
    echo "new-domain: ERROR — usage: new-domain.sh <domain-name> [--dry-run]" >&2
    exit 1
fi

if ! bash "$SCRIPT_DIR/validate-domain-name.sh" "$DOMAIN"; then
    exit 1
fi

# ── Prereq: METHODOLOGY.md must exist ────────────────────────────────────────
if [ ! -f "$REPO_ROOT/METHODOLOGY.md" ]; then
    echo "MISSING_METHODOLOGY: METHODOLOGY.md not found at $REPO_ROOT" >&2
    exit 1
fi

# ── Check domain does not already exist ──────────────────────────────────────
SPECS_DIR="$REPO_ROOT/specs"
for existing in "${DOMAIN}-l0.yaml" "${DOMAIN}-frontend-l0.yaml"; do
    if [ -f "$SPECS_DIR/$existing" ]; then
        echo "DOMAIN_EXISTS: specs/$existing already exists" >&2
        echo "  If it is an UNFILLED scaffold, run /ax-plan ${DOMAIN} to fill it (do not re-scaffold)." >&2
        echo "  Otherwise remove the existing scaffold files before re-scaffolding." >&2
        exit 1
    fi
done

# ── Build file plan (full_trio by default) ────────────────────────────────────
DOMAIN_UPPER="$(echo "$DOMAIN" | tr '[:lower:]-' '[:upper:]_')"
TODAY="$(date +%Y-%m-%d)"

declare -a FILES_TO_CREATE=(
    "specs/${DOMAIN}-l0.yaml"
    "specs/${DOMAIN}-frontend-l0.yaml"
    "contracts/${DOMAIN}-openapi.yaml"
    "contracts/${DOMAIN}-ui.yaml"
    "blueprints/${DOMAIN}-manifest.yaml"
    "blueprints/${DOMAIN}-ui-manifest.yaml"
    "templates/L4/${DOMAIN}/.gitkeep"
)

echo "=== ax-scaffold: new-domain.sh ==="
echo ""
echo "Domain:  $DOMAIN"
echo "Mode:    full_trio (default)"
echo "Root:    $REPO_ROOT"
echo ""
echo "File plan:"
for f in "${FILES_TO_CREATE[@]}"; do
    echo "  + $f"
done
echo ""

if [ "$DRY_RUN" -eq 1 ]; then
    echo "Dry-run mode: no files written."
    echo "new-domain: DRY-RUN COMPLETE (exit 0)"
    exit 0
fi

# ── Write scaffold files ──────────────────────────────────────────────────────

# specs/<domain>-l0.yaml — canonical BACKEND compliance spec (UNFILLED scaffold)
cat > "$REPO_ROOT/specs/${DOMAIN}-l0.yaml" <<YAML
# specs/${DOMAIN}-l0.yaml — Backend compliance spec (L0 scaffold — UNFILLED).
# Generated by ax-scaffold on ${TODAY}. This skeleton is BLOCKED by
# spec_scaffold_unfilled_guard.sh until you fill it: run /ax-plan ${DOMAIN} to
# replace the placeholder below with real items (id/chapter/requirement/
# test_method/verification_type/applicable/notes/policy_ref) + 1:1 RED @Tag stubs.
version: "0.1.0"
scope: "${DOMAIN} — TODO(/ax-plan): one-line scope"
domain_mode: full_trio   # TODO(/ax-plan): confirm full_trio | backend_only | frontend_only
stack: "Spring Boot 3.2.x"
standard: "TODO(/ax-plan): external standard(s) — OWASP/RFC/JEP/vendor"
items: []
# TODO: Add items — run /ax-plan ${DOMAIN}
YAML

# specs/<domain>-frontend-l0.yaml — frontend page-compliance spec (UNFILLED scaffold)
cat > "$REPO_ROOT/specs/${DOMAIN}-frontend-l0.yaml" <<YAML
# specs/${DOMAIN}-frontend-l0.yaml — Frontend page-compliance spec (L0 scaffold — UNFILLED).
# Generated by ax-scaffold on ${TODAY}. BLOCKED by spec_scaffold_unfilled_guard.sh
# until filled. Run /ax-plan ${DOMAIN}. (Delete this file if domain_mode is backend_only.)
version: "0.1.0"
scope: "${DOMAIN} frontend — TODO(/ax-plan): one-line scope"
domain_mode: full_trio   # TODO(/ax-plan): confirm full_trio | frontend_only
standard: "WCAG 2.2 + TODO(/ax-plan)"
items: []
# TODO: Add items — run /ax-plan ${DOMAIN}
YAML

# contracts/<domain>-openapi.yaml
cat > "$REPO_ROOT/contracts/${DOMAIN}-openapi.yaml" <<YAML
# contracts/${DOMAIN}-openapi.yaml — Backend OpenAPI contract (L0 draft)
# Generated by ax-scaffold on ${TODAY}.
openapi: "3.0.3"
info:
  title: "${DOMAIN} API"
  version: "0.1.0"
  description: "Generated scaffold — fill in paths and schemas."
paths: {}
# TODO: Add API paths following contracts/auth-openapi.yaml as reference
YAML

# contracts/<domain>-ui.yaml
cat > "$REPO_ROOT/contracts/${DOMAIN}-ui.yaml" <<YAML
# contracts/${DOMAIN}-ui.yaml — Frontend UI contract (L0 draft)
# Generated by ax-scaffold on ${TODAY}.
domain: ${DOMAIN}
version: "0.1.0"
generated: "${TODAY}"
routes: []
# TODO: Add UI route entries following contracts/auth-ui.yaml as reference
YAML

# blueprints/<domain>-manifest.yaml
cat > "$REPO_ROOT/blueprints/${DOMAIN}-manifest.yaml" <<YAML
# blueprints/${DOMAIN}-manifest.yaml — Backend policy manifest (L0 draft)
# Generated by ax-scaffold on ${TODAY}.
domain: ${DOMAIN}
version: "0.1.0"
generated: "${TODAY}"
policies: []
# TODO: Add policy entries following blueprints/auth-manifest.yaml as reference
YAML

# blueprints/<domain>-ui-manifest.yaml
cat > "$REPO_ROOT/blueprints/${DOMAIN}-ui-manifest.yaml" <<YAML
# blueprints/${DOMAIN}-ui-manifest.yaml — Frontend UI policy manifest (L0 draft)
# Generated by ax-scaffold on ${TODAY}.
domain: ${DOMAIN}
version: "0.1.0"
generated: "${TODAY}"
policies: []
# TODO: Add UI policy entries following blueprints/auth-ui-manifest.yaml as reference
YAML

# templates/L4/<domain>/.gitkeep
mkdir -p "$REPO_ROOT/templates/L4/${DOMAIN}"
touch "$REPO_ROOT/templates/L4/${DOMAIN}/.gitkeep"

echo "Files written successfully — this is an UNFILLED skeleton."
echo ""
echo "REQUIRED NEXT (the forcing wire — G006):"
echo "  ▶ Run  /ax-plan $DOMAIN  to fill+trace the Spec Trio before any implementation."
echo ""
echo "    Until you do, spec_scaffold_unfilled_guard.sh BLOCKS the build (the specs still"
echo "    carry the '# TODO: Add' scaffold marker). /ax-plan removes that marker by filling"
echo "    real items + emitting 1:1 RED @Tag stubs, then binds every item (binding guard)."
echo ""
echo "  /ax-plan handles, in order: (1) interview (domain_mode, standards, complexity),"
echo "    (2) fill specs/${DOMAIN}-l0.yaml (+ frontend spec) / contract / manifest,"
echo "    (3) register domain_mode in practices/evals/trio_integrity_allowlist.yaml,"
echo "    (4) emit RED @Tag stubs, (5) register the test${DOMAIN_UPPER:+}<Domain> Gradle task,"
echo "    (6) write docs/blueprints/$DOMAIN/{plan.md,progress.md}."
echo ""
echo "  THEN: implement (RED→GREEN) per docs/NEW-DOMAIN-CHECKLIST.md, then"
echo "    /ax-verify-domain $DOMAIN + ./gradlew test<Domain> + R25 verify-completion."
echo ""
echo "new-domain: SCAFFOLD COMPLETE — run /ax-plan $DOMAIN next (exit 0)"
exit 0
