#!/usr/bin/env bash
# skills/ax-scaffold/scripts/new-domain.sh — Tier-1 domain scaffolder.
#
# Generates the Spec Trio skeleton for a new domain per METHODOLOGY.md Appendix C.
# Accepts a required <domain> argument and an optional --dry-run flag.
#
# Exit 0 = files written (or plan printed in dry-run mode)
# Exit 1 = validation error (DOMAIN_EXISTS, INVALID_NAME, MISSING_METHODOLOGY)
#
# Usage:
#   bash skills/ax-scaffold/scripts/new-domain.sh <domain-name> [--dry-run]
set -uo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/../../.." && pwd)"

# ── Parse args ────────────────────────────────────────────────────────────────
DOMAIN=""
DRY_RUN=0

for arg in "$@"; do
    case "$arg" in
        --dry-run) DRY_RUN=1 ;;
        -*) echo "new-domain: ERROR — unknown flag: $arg" >&2; exit 1 ;;
        *)
            if [ -n "$DOMAIN" ]; then
                echo "new-domain: ERROR — multiple domain names provided: '$DOMAIN' and '$arg'" >&2
                exit 1
            fi
            DOMAIN="$arg"
            ;;
    esac
done

# ── Validate domain name ──────────────────────────────────────────────────────
if [ -z "$DOMAIN" ]; then
    echo "new-domain: ERROR — usage: new-domain.sh <domain-name> [--dry-run]" >&2
    exit 1
fi

if ! bash "$SCRIPT_DIR/validate-domain-name.sh" "$DOMAIN"; then
    exit 1
fi

# ── Prereq: METHODOLOGY.md must exist ────────────────────────────────────────
if [ ! -f "$REPO_ROOT/METHODOLOGY.md" ]; then
    echo "MISSING_METHODOLOGY: METHODOLOGY.md not found at $REPO_ROOT" >&2
    exit 1
fi

# ── Check domain does not already exist ──────────────────────────────────────
SPECS_DIR="$REPO_ROOT/specs"
EXISTING_SPEC="$SPECS_DIR/${DOMAIN}-frontend-l0.yaml"

if [ -f "$EXISTING_SPEC" ]; then
    echo "DOMAIN_EXISTS: specs/${DOMAIN}-frontend-l0.yaml already exists" >&2
    echo "  Remove existing scaffold files before re-scaffolding." >&2
    exit 1
fi

# ── Build file plan (full_trio by default) ────────────────────────────────────
DOMAIN_UPPER="$(echo "$DOMAIN" | tr '[:lower:]-' '[:upper:]_')"
TODAY="$(date +%Y-%m-%d)"

declare -a FILES_TO_CREATE=(
    "specs/${DOMAIN}-frontend-l0.yaml"
    "specs/${DOMAIN}-asvs-l0.yaml"
    "contracts/${DOMAIN}-openapi.yaml"
    "contracts/${DOMAIN}-ui.yaml"
    "blueprints/${DOMAIN}-manifest.yaml"
    "blueprints/${DOMAIN}-ui-manifest.yaml"
    "templates/L4/${DOMAIN}/.gitkeep"
)

echo "=== ax-scaffold: new-domain.sh ==="
echo ""
echo "Domain:  $DOMAIN"
echo "Mode:    full_trio (default)"
echo "Root:    $REPO_ROOT"
echo ""
echo "File plan:"
for f in "${FILES_TO_CREATE[@]}"; do
    echo "  + $f"
done
echo ""

if [ "$DRY_RUN" -eq 1 ]; then
    echo "Dry-run mode: no files written."
    echo "new-domain: DRY-RUN COMPLETE (exit 0)"
    exit 0
fi

# ── Write scaffold files ──────────────────────────────────────────────────────

# specs/<domain>-frontend-l0.yaml
cat > "$REPO_ROOT/specs/${DOMAIN}-frontend-l0.yaml" <<YAML
# specs/${DOMAIN}-frontend-l0.yaml — Frontend page-compliance spec (L0 draft)
# Generated by ax-scaffold on ${TODAY}. Fill in route_id, title, and rules.
domain: ${DOMAIN}
mode: full_trio
version: "0.1.0"
generated: "${TODAY}"
pages: []
# TODO: Add page entries following the pattern in specs/auth-frontend-l0.yaml
YAML

# specs/<domain>-asvs-l0.yaml
cat > "$REPO_ROOT/specs/${DOMAIN}-asvs-l0.yaml" <<YAML
# specs/${DOMAIN}-asvs-l0.yaml — Backend ASVS compliance spec (L0 draft)
# Generated by ax-scaffold on ${TODAY}. Fill in items following auth-asvs-l1.yaml.
domain: ${DOMAIN}
version: "0.1.0"
generated: "${TODAY}"
items: []
# TODO: Add ASVS items applicable to this domain
YAML

# contracts/<domain>-openapi.yaml
cat > "$REPO_ROOT/contracts/${DOMAIN}-openapi.yaml" <<YAML
# contracts/${DOMAIN}-openapi.yaml — Backend OpenAPI contract (L0 draft)
# Generated by ax-scaffold on ${TODAY}.
openapi: "3.0.3"
info:
  title: "${DOMAIN} API"
  version: "0.1.0"
  description: "Generated scaffold — fill in paths and schemas."
paths: {}
# TODO: Add API paths following contracts/auth-openapi.yaml as reference
YAML

# contracts/<domain>-ui.yaml
cat > "$REPO_ROOT/contracts/${DOMAIN}-ui.yaml" <<YAML
# contracts/${DOMAIN}-ui.yaml — Frontend UI contract (L0 draft)
# Generated by ax-scaffold on ${TODAY}.
domain: ${DOMAIN}
version: "0.1.0"
generated: "${TODAY}"
routes: []
# TODO: Add UI route entries following contracts/auth-ui.yaml as reference
YAML

# blueprints/<domain>-manifest.yaml
cat > "$REPO_ROOT/blueprints/${DOMAIN}-manifest.yaml" <<YAML
# blueprints/${DOMAIN}-manifest.yaml — Backend policy manifest (L0 draft)
# Generated by ax-scaffold on ${TODAY}.
domain: ${DOMAIN}
version: "0.1.0"
generated: "${TODAY}"
policies: []
# TODO: Add policy entries following blueprints/auth-manifest.yaml as reference
YAML

# blueprints/<domain>-ui-manifest.yaml
cat > "$REPO_ROOT/blueprints/${DOMAIN}-ui-manifest.yaml" <<YAML
# blueprints/${DOMAIN}-ui-manifest.yaml — Frontend UI policy manifest (L0 draft)
# Generated by ax-scaffold on ${TODAY}.
domain: ${DOMAIN}
version: "0.1.0"
generated: "${TODAY}"
policies: []
# TODO: Add UI policy entries following blueprints/auth-ui-manifest.yaml as reference
YAML

# templates/L4/<domain>/.gitkeep
mkdir -p "$REPO_ROOT/templates/L4/${DOMAIN}"
touch "$REPO_ROOT/templates/L4/${DOMAIN}/.gitkeep"

echo "Files written successfully."
echo ""
echo "Next steps:"
echo "  1. Add '$DOMAIN' to practices/evals/trio_integrity_allowlist.yaml"
echo "  2. Write TDD anchor test (RED) before any implementation"
echo "  3. Run /ax-verify-domain $DOMAIN to validate scaffold structure"
echo "  4. Commit scaffold files in a dedicated commit"
echo ""
echo "new-domain: COMPLETE (exit 0)"
exit 0
