/**
 * P1-73 fictional-field LOCK — executable, not manual.
 *
 * The cross-family final gate proved the original lock was prose: the PRD-required
 * repository scans (`grep -rn "verificationState\|providerLinks" templates/ frontend/`,
 * `rg 'roles\[\]'`) were only ever run by hand, so re-introducing the fictional
 * /auth/me shape in the lint/tsc-blind templates/L4 auth page (the fork-receiver
 * deliverable, outside every ESLint/tsc glob per P2-23) passed every AUTOMATED gate.
 * Reviewer's exact reproduction: map `data.roles?.[0]` / `data.verificationState` /
 * `data.providerLinks` back into the page's fetch adapter — view tests, BE golden
 * parity, lint and structural guards all stayed green while the dashboard rendered
 * empty role / unverified / no providers against the real backend.
 *
 * This test IS the scan, wired into `npm run test` and therefore into R25's
 * frontend step. It walks both trees itself; it does not trust anyone to run grep.
 *
 * The fictional tokens (and the P2-54 concat-detection fragments below) are
 * assembled via array + `.join('')` rather than string `+` concatenation — a
 * literal `'verification' + 'State'` in this file's own source is exactly the
 * shape the P2-54 concat check below hunts for in other files, so building our
 * own fixtures that way would risk this file tripping its own lock. `.join('')`
 * has no `+` between the quoted fragments, so it cannot match. (The `file ===
 * SELF` skip below already excludes this file from the scan by path, but the
 * fragment style is kept self-safe too, matching the original design intent.)
 */
import { describe, expect, it } from 'vitest'
import { readdirSync, readFileSync, statSync } from 'node:fs'
import { join, resolve, sep } from 'node:path'
import { execFileSync } from 'node:child_process'

const FRONTEND_ROOT = resolve(__dirname, '..')
const REPO_ROOT = resolve(FRONTEND_ROOT, '..')
const SCAN_ROOTS = [join(REPO_ROOT, 'templates'), FRONTEND_ROOT]
// P2-56: skip-dirs is a fixed list, so its members must each be justified (why
// this name is always a generated/vendored tree, never hand-authored source) —
// and the "tracked-source-dir" check below (in the describe block) makes the
// boundary honest: if any of these names is ever created as a real, git-tracked
// source directory, the lock must complain instead of silently skipping it.
const SKIP_DIRS = new Map([
  ['node_modules', 'npm-installed dependency tree — vendored, never hand-authored'],
  ['dist', 'tsc/vite/bundler build output — regenerated by `npm run build`'],
  ['build', 'generic build-tool output directory (framework build/export dirs)'],
  ['coverage', 'test coverage report output (istanbul/v8 html+json)'],
  ['.next', 'Next.js build cache/output directory — regenerated by `npm run build`'],
])
const SELF = resolve(__filename)

const FICTIONAL = [
  ['verification', 'State'].join(''),
  ['provider', 'Links'].join(''),
]
// property-ACCESS shapes too, not just the literal type annotation: `data.roles?.[0]`,
// `x.roles[0]`, `.roles.map(...)` — the final gate proved a role-only reintroduction
// evaded the literal-only token. Verified zero legitimate `.roles` uses in either tree.
const ROLES_RE = new RegExp('\\.' + ['roles'].join('') + '\\b|' + ['roles'].join('') + '\\[' + '\\]')

// P2-54: computed-access evasion. The lock above only catches the LITERAL token
// `verificationState` / `providerLinks`; `data["verification" + "State"]` builds
// the same property name at runtime and slips past a literal-token scan (this is
// the exact self-exemption trick this file itself used to use, turned into an
// evasion). This is a FINITE, honest boundary, not general computed-access
// detection (which is undecidable): it catches string-literal concatenation of
// these two specific fragment pairs, either quote style ('/"/`), with optional
// whitespace around the `+`. It does NOT catch — and cannot catch — arbitrary
// dynamic construction: variables, template interpolation, `String.fromCharCode`,
// base64/rot13, bracket-indexed lookup tables, etc. Anything beyond literal
// fragment-concat of these exact tokens is out of scope for this lock.
const CONCAT_RE = new RegExp(
  [
    ['verification', 'State'],
    ['provider', 'Links'],
  ]
    .map(([a, b]) => ['[\'"`]', a, '[\'"`]', '\\s*\\+\\s*', '[\'"`]', b, '[\'"`]'].join(''))
    .join('|'),
)

// collected across all walk() calls so the describe block below can audit them
const skippedDirPaths: string[] = []

function* walk(dir: string): Generator<string> {
  for (const name of readdirSync(dir)) {
    const full = join(dir, name)
    const st = statSync(full)
    if (st.isDirectory()) {
      if (SKIP_DIRS.has(name)) {
        skippedDirPaths.push(full)
        continue
      }
      yield* walk(full)
    } else if (/\.(js|jsx|ts|tsx)$/.test(name)) {
      yield full
    }
  }
}

describe('P1-73 canonical /auth/me shape lock (templates/ + frontend/, .js/.jsx/.ts/.tsx)', () => {
  const hits: string[] = []
  const rolesHits: string[] = []
  const concatHits: string[] = []

  for (const root of SCAN_ROOTS) {
    for (const file of walk(root)) {
      if (resolve(file) === SELF) continue
      const text = readFileSync(file, 'utf-8')
      // single regex pass per file (string membership, not array.includes-in-loop)
      const fictionalRe = new RegExp(FICTIONAL.join('|'), 'g')
      for (const m of text.match(fictionalRe) ?? []) {
        hits.push(`${file.split(REPO_ROOT + sep)[1] ?? file}: ${m}`)
      }
      if (ROLES_RE.test(text)) {
        rolesHits.push(file.split(REPO_ROOT + sep)[1] ?? file)
      }
      const concatMatch = text.match(CONCAT_RE)
      if (concatMatch) {
        concatHits.push(`${file.split(REPO_ROOT + sep)[1] ?? file}: ${concatMatch[0]}`)
      }
    }
  }

  it('no source file references the fictional verification/provider fields', () => {
    expect(hits, 'fictional /auth/me fields re-introduced — the real backend never ' +
      'sends these; the dashboard would silently render empty (see P1-73)').toEqual([])
  })

  it('no source file references the fictional roles array shape', () => {
    expect(rolesHits, 'the canonical shape has a single `role` string — any roles-' +
      'array access or annotation is the pre-P1-73 fiction').toEqual([])
  })

  it('no source file computed-concatenates the fictional field fragments (P2-54)', () => {
    expect(concatHits, 'a `"verification" + "State"` / `"provider" + "Links"` style ' +
      'string concatenation builds the same fictional property name at runtime, ' +
      'evading the literal-token scan above — see the P2-54 boundary comment near ' +
      'CONCAT_RE for what this does and does not cover').toEqual([])
  })

  it('the scan itself is non-vacuous (it actually visited both trees)', () => {
    // silence-is-not-success: an empty walk would vacuously pass the locks above
    // per-tree floors (the gate showed a single aggregate floor lets one whole
    // tree vanish): current counts are ~401 (templates) and ~432 (frontend)
    for (const root of SCAN_ROOTS) {
      let visited = 0
      for (const _ of walk(root)) visited++
      expect(visited, `scan tree vanished: ${root}`).toBeGreaterThan(100)
    }
  })

  it('no skip-dir name hides a real, git-tracked source directory (P2-56)', () => {
    // SKIP_DIRS is a fixed list of names that are assumed to always be generated/
    // vendored trees (see the rationale map above). That assumption could go stale
    // — someone could create e.g. `frontend/src/dist/` as a real source folder and
    // the walk would silently swallow it. Ground the assumption in git: any path
    // that got skipped during the walk above must have zero git-TRACKED source
    // files under it, or the skip-list is hiding real code, not just build output.
    const offenders: string[] = []
    // dedupe: the non-vacuous test below re-walks both roots, so the same
    // skipped path can be recorded more than once — that's a reporting nicety,
    // not a correctness issue, but a deduped report is easier to act on.
    for (const dir of new Set(skippedDirPaths)) {
      let tracked: string
      try {
        tracked = execFileSync('git', ['ls-files', '--', dir], {
          cwd: REPO_ROOT,
          encoding: 'utf-8',
        })
      } catch {
        // git unavailable in this environment — cannot assert either way, so
        // don't turn that into a false failure of an unrelated lock.
        continue
      }
      const trackedSource = tracked
        .split('\n')
        .filter((f) => /\.(js|jsx|ts|tsx)$/.test(f))
      if (trackedSource.length > 0) {
        offenders.push(
          `${dir.split(REPO_ROOT + sep)[1] ?? dir} (${trackedSource.length} tracked source file(s))`,
        )
      }
    }
    expect(offenders, 'a directory named like a generated/vendored tree ' +
      '(node_modules/dist/build/coverage/.next) contains git-tracked source files — ' +
      'the fixed skip-dir list is swallowing real source, not just build output').toEqual([])
  })
})
