#!/usr/bin/env bash
# templates/generate_agents.sh — produce templates/AGENTS.md by hashing DECISIONS.md
# and any *.md files under templates/L{1,2,3,4}/ and templates/backend/.
# Idempotent: a second run with no content changes produces no diff.
#
# Pattern mirrors practices/generate_agents.sh (sha256 sentinel in frontmatter).
set -euo pipefail

cd "$(dirname "$0")"

OUT="AGENTS.md"

# Collect files to include in the sentinel hash: DECISIONS.md + template layer markdowns.
SOURCE_FILES=()
[[ -f DECISIONS.md ]] && SOURCE_FILES+=("DECISIONS.md")
# Walk subdirs with find (portable)
while IFS= read -r f; do
    SOURCE_FILES+=("$f")
done < <(find L1 L2 L3 L4 backend -name "*.md" 2>/dev/null | sort)

# Sort for determinism
if [ "${#SOURCE_FILES[@]}" -gt 0 ]; then
    IFS=$'\n' SORTED=($(printf '%s\n' "${SOURCE_FILES[@]}" | sort -u)); unset IFS
else
    SORTED=()
fi

# Build concat for sha computation
CONCAT=""
for f in "${SORTED[@]}"; do
    [[ -f "$f" ]] && CONCAT="${CONCAT}$(cat "$f")"$'\n'
done

SHA="$(printf '%s' "$CONCAT" | shasum -a 256 | awk '{print $1}')"
COUNT="${#SORTED[@]}"

cat > "$OUT" <<AGENTS_EOF
---
sentinel:
  source_concat_sha256: "$SHA"
  source_file_count: $COUNT
  generated_by: "templates/generate_agents.sh"
  generated_at: "$(date -u +%Y-%m-%dT%H:%M:%SZ)"
---

# templates/ — AGENTS.md (auto-generated)

This file is auto-generated by \`templates/generate_agents.sh\`.
Do not edit by hand — re-run the script after changes to DECISIONS.md or any
template layer Markdown files.

## What this directory contains

\`templates/\` is the composition kit layer for ax-template. Structure:

\`\`\`
templates/
├── L1/        # shadcn/ui primitive wrappers + design tokens
├── L2/        # ax-template feature blocks (reusable across domains)
├── L3/        # Next.js 16 page template families
├── L4/        # domain workloads (1:1 with backend Spec Trio domains)
├── backend/   # Java cross-cutting templates
├── DECISIONS.md  # ADR provenance trail (TD-2026-05-17-001..010+)
└── AGENTS.md    # this file (sentinel)
\`\`\`

## Guard coverage

All files under \`templates/**\` are walked by:

- \`practices/evals/evidence_guard.sh\` — evidence: block required
- \`practices/evals/spec_ref_guard.sh\` — spec_ref field required
- \`practices/evals/substance_guard.sh\` — substance checks on rule bodies
- \`practices/evals/time_decay_guard.sh\` — upstream snapshot freshness
- \`practices/evals/trio_integrity_guard.sh\` — Frontend Spec Trio coverage
- \`practices/evals/cross_trio_guard.sh\` — L4→L1/L2/L3 import evidence

## ADR registry

See \`templates/DECISIONS.md\` for the full ADR trail (TD-2026-05-17-001..010).

## Sha256 source files ($COUNT total)

AGENTS_EOF

for f in "${SORTED[@]}"; do
    echo "- $f" >> "$OUT"
done

echo "wrote $OUT — $COUNT source files, sha=$SHA"
