/**
 * @ax-template-meta
 * template_id: backend/file-storage/FileStorageDto
 * layer: backend
 * domain: file-storage
 * anchors_rule: api-no-entity-leak.md
 * provenance_class: internal_design
 * evidence:
 *   - source_type: internal
 *     rationale: "Record-only DTO namespace for the domain. Realises specs/file-storage-l0.yaml#FILE-SEC-001 and #FILE-SEC-002: StoredFileResponse deliberately omits storageKey/storageBucket, so the internal storage path never crosses the controller boundary."
 */
package com.ax.template.authblueprint.filestorage;

import com.fasterxml.jackson.annotation.JsonInclude;

import java.time.Instant;
import java.util.List;
import java.util.UUID;

/**
 * DTOs for the file-storage domain.
 *
 * <p>StoredFileResponse deliberately omits {@code storageKey} and {@code storageBucket}
 * to prevent internal storage path leakage (FILE-SEC-001, FILE-SEC-002).
 */
public final class FileStorageDto {

    private FileStorageDto() {} // utility class — no instantiation

    // ─── Request ────────────────────────────────────────────────────────────

    /**
     * Metadata submitted alongside the multipart file upload.
     * The file binary is handled as a MultipartFile parameter in the controller.
     */
    public record UploadRequest(
            String description,
            List<String> tags
    ) {}

    // ─── Response ───────────────────────────────────────────────────────────

    /**
     * Public representation of a stored file.
     *
     * <p>NOTE: {@code storageKey} is intentionally absent — never include it here.
     * {@code downloadUrl} is a time-limited presigned URL generated by PresignedUrlService;
     * it is null for non-READY files.
     */
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public record StoredFileResponse(
            UUID id,
            String name,
            String contentType,
            long sizeBytes,
            FileStatus status,
            String description,
            List<String> tags,
            Instant uploadedAt,
            Instant expiresAt,
            String downloadUrl   // null if status != READY
    ) {}

    /**
     * Paginated response for the file list endpoint.
     */
    public record StoredFilePageResponse(
            List<StoredFileResponse> content,
            long totalElements,
            int totalPages,
            int page,
            int size
    ) {}
}
